2020/12/07 18:46:22 [error] 19303#19303: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 121.145.188.227, server: api.dandiventure.com, request: "GET /auth/admin HTTP/1.1", upstream: "http://127.0.0.1:3000/auth/admin", host: "api.dandiventure.com"
2020/12/07 18:46:22 [error] 19303#19303: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 121.145.188.227, server: api.dandiventure.com, request: "GET /auth/admin HTTP/1.1", upstream: "http://[::1]:3000/auth/admin", host: "api.dandiventure.com"
2020/12/07 18:46:29 [error] 19303#19303: *39 no live upstreams while connecting to upstream, client: 121.145.188.227, server: api.dandiventure.com, request: "GET /auth/admin HTTP/1.1", upstream: "http://localhost/auth/admin", host: "api.dandiventure.com"
